version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: nc_postgres
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data/db-files/
    ports:
      - 5432:5432
    env_file: .env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    links:
      - "postgresql:postgresql-server"
    env_file: .env
    ports:
      - '5555:80'
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: